version: "3"

services:
  qiaoqian-backend:
    build:
      context: .
      dockerfile: ./local/Dockerfile
    image: qiaoqian-backend-local
    container_name: qiaoqian-backend-local
    working_dir: /qiaoqian-backend
    tty: true
    stdin_open: true
    volumes:
      - .:/qiaoqian-backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: /start.sh