from UserCenter.views.register import *
from UserCenter.views.login import *
from UserCenter.views.change_user_name import *
from UserCenter.views.change_user_avatar import *
from UserCenter.views.add_album import *
from UserCenter.views.delete_album import *
from UserCenter.views.getImagesInfo import *
from UserCenter.views.change_album_name import *
from UserCenter.views.delete_image import *
from UserCenter.views.delete_sticker import *
from UserCenter.views.add_image import *
from UserCenter.views.add_sticker import *
from UserCenter.views.get_image_base64 import *
from UserCenter.views.change_password import *
